### PR TITLE
Fix for Angular 5

### PR DESCRIPTION
**Pull request by jakehockey10**
This is to address the issue open marked as a bug.  To test this (since I don't know how to write the tests myself), I made the fix, replaced the node_module in my Angular 5 application's node_modules folder and served it up.  I no longer received this issue with the references changed to imports.

I also moved the @types node modules to dev dependencies.  

I also updated the libraries to their latest versions

### CODE REVIEW

**Comment by jakehockey10** [comment]
#2

**Comment by byWulf** [comment]
Ty for the pull request. I need to verify that this is no breaking change for existing solutions (f.e. the pure HTML/JavaScript implementation). Don't have time for it right now, but in a few weeks I will test it :)

**Comment by pgorczynski-df** [comment]
Hi @byWulf , I like your project and wanted to make use of it 👍 
Can you accept this PR and release a new version, please? :)

**Comment by byWulf** [comment]
Sorry for the very late response! Just released 1.1.0, please try it out if everything works as expected :)

**Pull request merged**
